### PR TITLE
Add `start_version` and `cdf_enabled` support for `databricks_share`

### LINKED ISSUE #2003: [ISSUE] Incorrect diff detection in `databricks_share` resource
It seems that the detection of diffs in the `databricks_share` is incorrect. It generates a diff every time I try to apply TF even if the configuration does not change.

### Configuration
```yaml
databricks_share:
      share_to_xxx:
        name: share_to_XXX
        object:
        - data_object_type: TABLE
          name: main.default.XXX1
        - data_object_type: TABLE
          name: main.default.XXX1
```

### Expected Behavior
No diff is found after the first terraform apply.

### Actual Behavior
Diff generated with every apply:
```
# databricks_share.share_to_system_tables will be updated in-place
  ~ resource "databricks_share" "share_to_xxx" {
        created_at = 1676380776020
        created_by = "XXX"
        id         = "share_to_XXX"
        name       = "share_to_XXX"

      - object {
          - added_at         = 1676380776426 -> null
          - added_by         = "XXX" -> null
          - data_object_type = "TABLE" -> null
          - name             = "main.default.XXX1" -> null
          - shared_as        = "default.XXX1" -> null
        }
      - object {
          - added_at         = 1676380776410 -> null
          - added_by         = "XXX" -> null
          - data_object_type = "TABLE" -> null
          - name             = "main.default.XXX2" -> null
          - shared_as        = "default.XXX2" -> null
        }
      + object {
          + added_at         = (known after apply)
          + added_by         = (known after apply)
          + data_object_type = "TABLE"
          + name             = "main.default.XXX1"
          + shared_as        = (known after apply)
        }
      + object {
          + added_at         = (known after apply)
          + added_by         = (known after apply)
          + data_object_type = "TABLE"
          + name             = "main.default.XXX2"
          + shared_as        = (known after apply)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce
`terraform apply` twice.

### Terraform and provider versions
1.9.1
### Debug Output
N/A

### Important Factoids
N/A

### LINKED ISSUE #2004: [FEATURE] Add support for Partitions, CDF & History for `databricks_share`
Delta Sharing has Advanced table options, which needs to be supported via Terraform - `cdf_enabled` and `start_version`

Usage would be

```hcl
resource "databricks_share" "some" {
  name = "my_share"
  dynamic "object" {
    for_each = data.databricks_tables.things.ids
    content {
      name             = object.value
      data_object_type = "TABLE"
      history_data_sharing_status = "ENABLED"
      cdf_enabled = true
    }
  }
}
```

### PR DESCRIPTION
**Pull request by nkvuong**
Closes #2004

Also fix diff detection, closes #2003

### CODE REVIEW

**Comment by nkvuong** [comment]
acceptance tests also passed

**Review by alexott — APPROVED** [review]
looks good. The only a bit of worry that upgrade from `slice_set` to `slice` may lead to user's confusion, but that could be ok - we had similar thing DLT pipelines.

**Comment by marekbrysa** [comment]
@nkvuong thanks for the quick implementation!
I don't think this should close https://github.com/databricks/terraform-provider-databricks/issues/2004 because AFAICT it does not implement `history_data_sharing_status`? Or would it be better to split the issue?

**Comment by nkvuong** [comment]
@marekbrysa I missed that one, as `history_data_sharing_status` was not in the API doc - let me quickly add it to this PR and test it

**Review by nfx — APPROVED** [review]

**Pull request merged**
