### PR TITLE
[DOCS] change master to main & GH image raw links

### PR DESCRIPTION
**Pull request by apd-bbrewington**
## Changes

- Change branch `master` to `main` in GitHub links
- Change raw links (for consistency with rest of repo)
  - from: `https://github.com/databricks/terraform-provider-databricks/raw`
  - to: `https://raw.githubusercontent.com/databricks/terraform-provider-databricks`

## Tests

I manually clicked through each new link to make sure it works

## Other Notes

Note on `docs/resources/permissions.md` --> `resource_permissions.go` link - this file no longer exists on main, and I decided to change from master to main anyway.  Here's permalink to last time I see this in commit history: https://github.com/databricks/terraform-provider-databricks/blob/41ea13b5605278c115dba30092d66c814d7c9791/access/resource_permissions.go#L261-L271

Maintainers, I'm glad to track down what that should be updated to.  Please lmk in comments

### CODE REVIEW

**Comment by apd-bbrewington** [comment]
Here's how it currently looks on Terraform Registry:

Screenshot 2024-03-10 at 3 15 46 PM

I went into HTML and manually changed `master` to `main`, and now the image shows up (thinking because Terraform docs site can't handle redirects once it pings GitHub.com for the file):

Screenshot 2024-03-10 at 3 18 28 PM

**Review by alexott — APPROVED** [review]
Thank you!

**Comment by alexott** [comment]
Regarding permissions - it should be https://github.com/databricks/terraform-provider-databricks/blob/main/permissions/resource_permissions.go#L324-L332

**Comment by apd-bbrewington** [comment]
@alexott fixed the resource_permissions.go link and merged main into this one.  should be good to go!

**Pull request merged**
