### PR TITLE
Bump Go SDK -> 0.16.0

### PR DESCRIPTION
**Pull request by mgyucht**
## Changes
Bump the Go SDK to 0.16.0. This includes, among other things, fixes to UC resource structures that unblocks implementing account-level UC resources.

## Tests

- [x] `make test` run locally
- [ ] relevant change in `docs/` folder
- [ ] covered with integration tests in `internal/acceptance`
- [ ] relevant acceptance tests are passing
- [ ] using Go SDK

### CODE REVIEW

**Review by nkvuong — APPROVED** [review]
lgtm

**Review by alexott — APPROVED** [review]
Looks good, but are integration tests passing?

**Comment by mgyucht** [comment]
Good point, let me trigger them.

**Comment by nkvuong** [comment]
All integration tests passed

**Pull request merged**
