### PR TITLE
Port `databricks_node_type` data source to Go SDK

### PR DESCRIPTION
**Pull request by alexott**
Please note that we can't use `WorkspaceData` here because we need to provide a request as schema, and we can't inherit from it.

### CODE REVIEW

**Comment by alexott** [comment]
Acceptance tests on all clouds are passed

**Comment by nfx** [comment]
@alexott updated SDK with the id change you've pushed

**Comment by alexott** [comment]
@nfx it's ready

**Comment by alexott** [comment]
Hmmm, acceptance tests are failing

**Review by nfx — APPROVED** [review]
thank you!

**Comment by nfx** [comment]
integration tests passed

**Pull request merged**
