### PR TITLE
Release v1.42.0

### PR DESCRIPTION
**Pull request by mgyucht**
### New Features and Improvements
* Allow changes to `display_name` for `databricks_service_principal` ([#3523](https://github.com/databricks/terraform-provider-databricks/pull/3523)).
* Modify `databricks_repo` to support Git folders in the workspace ([#3447](https://github.com/databricks/terraform-provider-databricks/pull/3447)).
* Retry requests in the Databricks Go SDK until context timeout ([#3537](https://github.com/databricks/terraform-provider-databricks/pull/3537)).
* Set ForceSendFields for boolean/integer values explicitly set to false/0 ([#3385](https://github.com/databricks/terraform-provider-databricks/pull/3385)).

### Bug fixes
* Added `ConflictsWith` to legacy tasks in `databricks_job` to avoid errors when job parameters are used ([#3500](https://github.com/databricks/terraform-provider-databricks/pull/3500)).
* Fixed spn secret permanent diff ([#3525](https://github.com/databricks/terraform-provider-databricks/pull/3525)).
* Introduced `common.NoClientData` helper function and use it in `databricks_aws_crossaccount_policy` data source to allow its use with workspace- or account-level providers ([#3508](https://github.com/databricks/terraform-provider-databricks/pull/3508)).
* Set `id` attribute of `databricks_metastore` data source ([#3503](https://github.com/databricks/terraform-provider-databricks/pull/3503)).

### Documentation Changes
* Added documentation for compute options for tasks in `databricks_job` resource ([#3504](https://github.com/databricks/terraform-provider-databricks/pull/3504)).
* Added warning about depends_on order ([#3489](https://github.com/databricks/terraform-provider-databricks/pull/3489)).
* Fixed various doc typos ([#3512](https://github.com/databricks/terraform-provider-databricks/pull/3512)).
* Fixed `databricks_current_metastore` data source names in docs examples ([#3515](https://github.com/databricks/terraform-provider-databricks/pull/3515)).
* Improved Job documentation structure ([#3511](https://github.com/databricks/terraform-provider-databricks/pull/3511), [#3536](https://github.com/databricks/terraform-provider-databricks/pull/3536), [#3535](https://github.com/databricks/terraform-provider-databricks/pull/3535)).
* Removed confusing mention of cloud types for `databricks_clusters` and `databricks_sql_warehouses` data sources ([#3518](https://github.com/databricks/terraform-provider-databricks/pull/3518)).

### Exporter
* Added UC support for DLT pipelines ([#3494](https://github.com/databricks/terraform-provider-databricks/pull/3494)).
* Ignored instance pools with the empty name ([#3522](https://github.com/databricks/terraform-provider-databricks/pull/3522)).

### Internal Changes
* Added DATABRICKS_USER_AGENT_EXTRA ([#3520](https://github.com/databricks/terraform-provider-databricks/pull/3520)).
* Adjusted list of supported platforms in `godownloader-databricks-provider.sh` ([#3527](https://github.com/databricks/terraform-provider-databricks/pull/3527)).
* Switched to Go SDK for `databricks_directory` resource and data source ([#3509](https://github.com/databricks/terraform-provider-databricks/pull/3509)).
* Fixed codecov for repository ([#3530](https://github.com/databricks/terraform-provider-databricks/pull/3530)).

Dependency updates:

 * Bump databricks-sdk-go to v0.40.0 ([#3534](https://github.com/databricks/terraform-provider-databricks/pull/3534)).

### CODE REVIEW

**Review by tanmay-db — APPROVED** [review]
There is _openapi_sha and .gitattributes files which probably shouldn't be there

**Review by alexott — APPROVED** [review]
lgtm, only may need to remove not necessary files

**Comment by landlord-matt** [comment]
Maybe we could include these doc improvements as well. https://github.com/databricks/terraform-provider-databricks/pull/3536 https://github.com/databricks/terraform-provider-databricks/pull/3535 . They iterate on the general structure improvement

**Comment by mgyucht** [comment]
@tanmay-db @alexott the unnecessary files are added by the release tooling that we have today. It should be alright to include these, as they don't interfere with anything. Otherwise, we'd need to further customize the tooling for this edge case, which IMO isn't necessarily worth it as it just leads to more cases we need to support & more complexity in the tool.

@landlord-matt No problem. I'll make sure those are in.

**Pull request merged**
