### PR TITLE
Bump github.com/databricks/databricks-sdk-go from 0.22.0 to 0.23.0

### PR DESCRIPTION
**Pull request by nkvuong**
## Changes

Bump go sdk, and other dependencies

## Tests

- [x] `make test` run locally
- [x] covered with integration tests in `internal/acceptance`
- [x] relevant acceptance tests are passing
- [x] using Go SDK

### CODE REVIEW

**Review by alexott — APPROVED** [review]
lgtm

**Comment by alexott** [comment]
The main problem with `suppress_diff` is that you can't completely remove the set value :-( I'm talking about diff on SQL query. Maybe we need to document it

**Comment by nkvuong** [comment]
@alexott the `sql_query` error is not related to the sdk bump, so I'll revert this change for now

**Comment by alexott** [comment]
@nkvuong I'm ok with this change, just maybe we'll need to document it clearly

**Comment by nkvuong** [comment]
integration tests passed, failed tests due to API behaviour change for `databricks_sql_query`

**Review by tanmay-db — APPROVED** [review]

**Pull request merged**
