### PR TITLE
Release v1.43.0

### PR DESCRIPTION
**Pull request by tanmay-db**
### New Features and Improvements
* Added state upgrader to remove `max_clusters_per_user` and ebs volume attributes set to zero ([#3551](https://github.com/databricks/terraform-provider-databricks/pull/3551)).
* Robust retries for workspace get-status ([#3550](https://github.com/databricks/terraform-provider-databricks/pull/3550)).
* Updated data_aws_crossaccount_policy to format resource string with account and region ([#3544](https://github.com/databricks/terraform-provider-databricks/pull/3544)).
* Fixed Issue: The field `node_type_id` cannot be supplied when an instance pool ID is provided ([#3549](https://github.com/databricks/terraform-provider-databricks/pull/3549))

### Documentation Changes
* Fixed error message typo in mounts.go ([#3552](https://github.com/databricks/terraform-provider-databricks/pull/3552)).
* State the options for run_if ([#3548](https://github.com/databricks/terraform-provider-databricks/pull/3548)).

### Exporter
* Don't emit all UC objects when handling dependencies ([#3556](https://github.com/databricks/terraform-provider-databricks/pull/3556)).
* Track removed objects during the `Emit` phase ([#3554](https://github.com/databricks/terraform-provider-databricks/pull/3554)).
* Optimize generation of `databricks_group_member` resource ([#3559](https://github.com/databricks/terraform-provider-databricks/pull/3559)).
* Included some UC objects into default listing ([#3565](https://github.com/databricks/terraform-provider-databricks/pull/3565))

### Internal Changes
* Jobs GoSDK schema migration ([#3532](https://github.com/databricks/terraform-provider-databricks/pull/3532)).
* Stabilize integration tests ([#3542](https://github.com/databricks/terraform-provider-databricks/pull/3542)).

### CODE REVIEW

**Comment by alexott** [comment]
We need to include https://github.com/databricks/terraform-provider-databricks/pull/3565 as well - it's a follow-up for https://github.com/databricks/terraform-provider-databricks/pull/3556 to handle UC objects correctly.

**Review by alexott — APPROVED** [review]

**Review by hectorcast-db — APPROVED** [review]

**Comment by landlord-matt** [comment]
I promise it will be the last one for a while, but one final fix for the job documentation to include https://github.com/databricks/terraform-provider-databricks/pull/3543

**Comment by tanmay-db** [comment]
Hi @landlord-matt, thanks for the PR, I will take a look.

**Comment by landlord-matt** [comment]
@tanmay-db: I addressed your feedback. It should be ready to merge now

**Review by andrewnester — APPROVED** [review]

**Comment by tanmay-db** [comment]
One test is failing due to immediate read after write when service principal is renamed. The rename is successful but old data is fetched and there is diff leading to failure. There was a successful run for this test yesterday, going ahead with the release since it doesn't seem related to the changes in TF.

**Comment by tanmay-db** [comment]
Hi @landlord-matt, thanks for the update, I will take a look at it today.

**Pull request merged**
