### PR TITLE
expand documentation for `databricks_sql_query` resource

### PR DESCRIPTION
**Pull request by crankswagon**
## changes to `databricks_sql_query` resource documentation

- add more examples for `parameter` blocks to make it easier for users
- add trouble shooting section to triage questions around `internal server errors`

## ~~other changes~~

~~general linting for `/docs` so new contributors should not longer see `hcl` parse errors when running `make fmt-docs`~~

linting moved to https://github.com/databricks/terraform-provider-databricks/pull/1606

### CODE REVIEW

**Review by alexott — APPROVED** [review]
lgtm

**Comment by crankswagon** [comment]
> lgtm

thank you @alexott, anything else i need to do on my end for `merge`? (im not authorized to merge PRs on this repo)

**Review by nfx — APPROVED** [review]

**Review by nfx — CHANGES_REQUESTED** [review]
@crankswagon 
* please separate make fmt-doc and sql query improvements into two separate PRs
* once you rebase on the latest master, i'll merge the pr

**Comment by crankswagon** [comment]
> @crankswagon thank you for keeping docs sane! :)
> 
> * please separate make fmt-doc and sql query improvements into two separate PRs
> * once you rebase on the latest master, i'll merge the pr

no worries at all :)

i've limited this PR to just `sql-query.md`

the other linting changes have been moved to https://github.com/databricks/terraform-provider-databricks/pull/1606

both have been rebased on the latest master 👍

**Review by nfx — APPROVED** [review]

**Comment by nfx** [comment]
@crankswagon previous PR merged, please rebase this one again

**Comment by crankswagon** [comment]
> @crankswagon previous PR merged, please rebase this one again

@nfx thank you, rebased just now 👍

**Pull request merged**
