### PR TITLE
[Feature] Update databricks_permissions resource to support vector-search-endpoints

### PR DESCRIPTION
**Pull request by zgcalebp**
## Changes
Databricks permissions API has been updated to support `vector-search-endpoints`. This corresponding change to the permissions_definitions would enable the use of the `databricks_permissions` resource to manage ACLs for Vector Search Endpoints leveraging the existing APIs under the hood.

Example CLI call confirming support: 
```
databricks permissions get vector-search-endpoints {endpoint-id} --debug
18:56:25  INFO start pid=77800 version=0.224.1 args="databricks, permissions, get, vector-search-endpoints, {endpoint-id}, --debug"
18:56:25  INFO Ignoring pat auth, because databricks-cli is preferred pid=77800 sdk=true
18:56:25  INFO Ignoring basic auth, because databricks-cli is preferred pid=77800 sdk=true
18:56:25  INFO Ignoring oauth-m2m auth, because databricks-cli is preferred pid=77800 sdk=true
18:56:25  INFO Refreshed OAuth token from Databricks CLI, expires on 2024-11-11 19:00:53.515729 -0500 EST pid=77800 sdk=true
18:56:25 DEBUG Using Databricks CLI authentication with Databricks OAuth tokens pid=77800 sdk=true
18:56:25  INFO Refreshed OAuth token from Databricks CLI, expires on 2024-11-11 19:00:53.515729 -0500 EST pid=77800 sdk=true
18:56:26 DEBUG GET /api/2.0/permissions/vector-search-endpoints/{endpoint-id}
< HTTP/2.0 200 OK
< {
<   "access_control_list": [
....
```

## Tests

- [X] `make test` run locally
- [X] relevant change in `docs/` folder
- [x] covered with integration tests in `internal/acceptance`
- [ ] relevant acceptance tests are passing
- [X] using Go SDK

### CODE REVIEW

**Review by alexott — COMMENTED** [review]
changes looks good - thank you. 

can you please add a permission resource inside this integration test: https://github.com/databricks/terraform-provider-databricks/blob/main/internal/acceptance/vector_search_test.go#L20?

**Comment by alexott** [comment]
And please do `make fmt`

**Comment by zgcalebp** [comment]
Sorry for the typos on that last commit 😅 . Working through getting these integration tests to run locally now. Thanks for the quick review too!

**Comment by zgcalebp** [comment]
Thanks @alexott for the test update. Should've more strongly considered the provisioning time for a permissions test.

**Comment by zgcalebp** [comment]
Is there some way to view the output of the integration tests? Surprised they aren't passing, happy to update to fix.

**Comment by alexott** [comment]
@zgcalebp The tests were failing because I ran the original patch with full-blown permissions test, but VS requires UC, and the test name wasn't adjusted for running only on UC-enabled workspaces

**Review by alexott — APPROVED** [review]

**Pull request merged**
