### PR TITLE
fix: do not attempt to delete default schema for foriegn catalogs

### LINKED ISSUE #2621: [ISSUE] Issue with `databricks_catalog` resource "cannot remove new catalog default schema"
### Configuration
```hcl
resource "databricks_connection" "mysql" {
  name            = "mysql"
  connection_type = "MYSQL"
  comment         = "This is a connection to mysql database"
  options = {
    host     = "prod-db.com"
    port     = "3306"
    user     = "username"
    password = "password"
  }
}

resource "databricks_catalog" "mysql" {
  metastore_id = "some id"
  name         = "mysql"
  comment      = "this catalog is managed by terraform"
  connection_name = databricks_connection.mysql.name
}
```

### Expected Behavior
Foreign mysql catalog is created without error.

### Actual Behavior
`Error: cannot create catalog: cannot remove new catalog default schema: Schema 'mysql.default' does not exist.`
Error occurs during creation, although the resource is correctly created in databricks.

### Steps to Reproduce
terraform apply the above catalog/connection.

### Terraform and provider versions
Terraform v1.5.1
on darwin_arm64
+ provider registry.terraform.io/databricks/databricks v1.24.0
+ provider registry.terraform.io/hashicorp/aws v5.14.0

### Debug Output
│ Error: cannot create catalog: cannot remove new catalog default schema: Schema 'mysql.default' does not exist.
│ 
│   with databricks_catalog.mysql[0],
│   on federation.tf line 19, in resource "databricks_catalog" "mysql":
│   19: resource "databricks_catalog" "mysql_prod" {

### Important Factoids
Looks like this is happening because it's checking for a ShareName, where if it doesn't exist, delete the default schema. 
https://github.com/databricks/terraform-provider-databricks/blob/b52c2645bd6b8ce83bb1584feb9220386d68db79/catalog/resource_catalog.go#L68 
This check for ShareName should probably also exclude Foreign Catalogs.

I'll go ahead and propose a PR to resolve this.

### PR DESCRIPTION
**Pull request by adam133**
## Changes
Close #2621 

## Tests

- [x] `make test` run locally
- [x] relevant change in `docs/` folder (N/A)
- [x] covered with integration tests in `internal/acceptance`
- [ ] relevant acceptance tests are passing
- [ ] using Go SDK

### CODE REVIEW

**Comment by adam133** [comment]
I have not developed Go code before, this may not be the correct change to make this work. Happy to make changes but I assume there's more changes to fix this.

**Comment by adam133** [comment]
> @adam133 thank you for your contribution - do you mind adding a couple of unit tests to resource_catalog_test.go? It should be similar to TestCatalogCreateAlsoDeletesDefaultSchema

@nkvuong I've added a test that should cover it, and got it passing locally. I didn't get _all_ tests passing, (there were 4 failing, something to do with local auth config), or something to do with Go config...

**Comment by nkvuong** [comment]
@adam133 could you run `make fmt` as well, so linting does not fail?

**Comment by adam133** [comment]
> @adam133 unit tests are passing, but could you run `make fmt` as well, so linting does not fail?

Done!

**Comment by ranjitha-shenoy** [comment]
Hi is there an ETA for this fix or any known workaround? We are also facing the same issue trying to create foreign catalog.

**Review by nkvuong — APPROVED** [review]
thanks for the contribution

**Comment by adam133** [comment]
> Hi is there an ETA for this fix or any known workaround? We are also facing the same issue trying to create foreign catalog.

@ranjitha-shenoy Depending on your CD process - for me the catalog was created as expected even though terraform reported that it had failed. Then I commented out the catalog resource from the terraform for until this bug is fixed. But any dependent resources/permissions probably won't work this way.

This PR should be ready to merge once we get the right approvals... then it'll need to wait for a release.

**Review by tanmay-db — APPROVED** [review]

**Pull request merged**
