### PR TITLE
Improve `databricks_group` documentation

### PR DESCRIPTION
**Pull request by fuselessmatt**
I found the previous documentation very confusing and this documentation would have [prevent this issue](https://github.com/databricks/terraform-provider-databricks/issues/1754) that I also had.

In summary 
* The documentation now use the official terminology account groups and workspace-local groups. This is better than the imprecise "creating a group in the account" as the workspace is also in the account. 
* The instructions states that you need to specify the host to create account groups, but in you also need account_id.

### CODE REVIEW

**Comment by fuselessmatt** [comment]
Once we can agree on the phrasing of the instructions, we should add it to https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/group_member which as the same problem

**Comment by daniel-anova** [comment]
Please make it clearer that account_id is supposed to contain an actual value and where to get it from.

**Comment by fuselessmatt** [comment]
Do we have any update on the review status of  this @PaulCornellDB ? An alternative solution would be to centralise the account vs workspace provider to a separate document somewhere, but that is a bigger change.

**Review by alexott — APPROVED** [review]
lgtm, thank you

@nfx fyi

**Pull request merged**
