### PR TITLE
[Fix] Force send fields for settings resources

### LINKED ISSUE #3976: Issue with `databricks_automatic_cluster_update_workspace_setting` resource
### Configuration

```hcl
# Copy-paste your Terraform configuration here

terraform {
  required_providers {
    databricks = {
      source = "databricks/databricks"
    }
  }
}

provider "databricks" {
  host  = "https://adb-509297107369812.12.azuredatabricks.net/"
  token = "dapi4276c4dc-2"
}

resource "databricks_automatic_cluster_update_workspace_setting" "this" {
  automatic_cluster_update_workspace {
    enabled                              = true
    restart_even_if_no_updates_available = true
    maintenance_window {
      week_day_based_schedule {
        day_of_week = "MONDAY"
        frequency   = "EVERY_WEEK"
        window_start_time {
          hours   = 1
          minutes = 0
        }
      }
    }
  }
}
```

### Expected Behavior

- It should enable the setting and configure the defined maintenance_window policy 

### Actual Behavior

- It successfully enabled the setting but failed to configure the maintenance_window policy of the schedule 

image

### Steps to Reproduce

 % terraform version
Terraform v1.9.5
on darwin_arm64  provider registry.terraform.io/databricks/databricks v1.51.0
%
1. Create the code
2. terraform apply
3. log in to the account console of Databricks and check the settings and policy

### Is it a regression?

NA

### Debug Output

https://gist.github.com/shashank853/48ae4bc7ba0fc5424fe95b70d664f569#file-debug-logs

### Important Factoids

NA

### Would you like to implement a fix?

NA

### PR DESCRIPTION
**Pull request by alexott**
## Changes

There was a problem that `databricks_automatic_cluster_update_setting` wasn't applied because `minutes` attribute was set to 0, and it wasn't sent in the JSON payload because it's marked as `omitempty` in the API.  After analysis, it was found that there are other places where we need to send data but the corresponding fields were marked as `omitempty`.

This PR includes following changes:

- in 3 resources force sending of boolean and numeric fields with 0 values
- add customize schema for `databricksenhanced_security_monitoring_setting`, `databricks_automatic_cluster_update_setting` and `databricks_enhanced_security_monitoring_setting` as fields are declared as required in documentation/API, but not enforced in Terraform because they are marked as `omitempty`
- expand documentation to include necessary blocks

Resolves #3976

## Tests

- [x] `make test` run locally
- [x] relevant change in `docs/` folder
- [ ] covered with integration tests in `internal/acceptance`
- [ ] relevant acceptance tests are passing
- [x] using Go SDK

### CODE REVIEW

**Review by mgyucht — APPROVED** [review]
Thank you for addressing this!

**Comment by aryah55** [comment]
This fix of making these settings mandatory broke our existing pipelines. Would have expected these settings on the Azure RM Provider for the workspace as you can set them on the azure portal as we had prior to these new resources being availalble for the  enhanced sec monitoring and compliance.

We had to change our interanl module for databricks workspace to match the settings as set in the Azure Portal to fix our pipelines.

**Comment by alexott** [comment]
Can you explain further what was broken and add the logs? This feature, enabled via Databricks API and enabled with Azure, differs a bit.

**Comment by aryah55** [comment]
Hi Alex, I did have an issue open but closed it on our fix. 

Full Details here with logs and steps and error recieved on provider update.
https://github.com/databricks/terraform-provider-databricks/issues/4060

We enabled it from the Azure Portal with None as the compliance profile a while back in our Development enviornments.

**Comment by alexott** [comment]
These are different issues imho... The problem solved by this PR was that TF didn't send the all necessary fields if they had "zero" value (`false`, `0`, ...)

**Pull request merged**
