### PR TITLE
Deprecate top level task attributes

### LINKED ISSUE #2978: [ISSUE] Issue with `databricks_job` resource `max_retries` attribute on the job object
For the `databricks_job` resource there is [an attribute at job level called `max_retries`](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/job#max_retries) (not to be confused with `max_retries` at task level). It seems that the job level `max_retries` attribute is only relevant for legacy Databricks jobs (jobs that use 2.0 API).

If a user wants to create a job within Terraform now, it will use the 2.1 jobs API where this attribute will not be used. This is evident in the following trace logs:

```bash
2023-12-01T16:13:55.692+0100 [WARN]  Provider "provider[\"registry.terraform.io/databricks/databricks\"]" produced an unexpected new value for databricks_job.this, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .max_retries: was cty.NumberIntVal(2), but now cty.NumberIntVal(0)
```

However, this could cause some confusion, because our documentation states that the job-level `max_retries` attribute is possible.

### Configuration

```hcl
resource "databricks_job" "this" {
  name        = "Job with multiple tasks"
  max_retries = 2 # <- The issue

  task {
    task_key = "a"
    new_cluster {
      num_workers   = 1
      spark_version = data.databricks_spark_version.latest_lts.id
      node_type_id  = data.databricks_node_type.smallest.id
    }

    notebook_task {
      notebook_path = "/Path/To/Notebook"
    }
  }
```

### Expected Behavior
We should remove it from the documentation and mark this attribute as deprecated, since I don't think the legacy Databricks 2.0 jobs API is being used anymore within Terraform.

### Actual Behavior
The `max_retries` attribute is being ignored since it is not a valid attribute for Databricks 2.1 jobs API

### Steps to Reproduce
1. `terraform apply`-->
2. (Optional) `terraform apply` again and see that max_retries is set to 0, asking to be changed to 2 again. 
``` 
# databricks_job.this will be updated in-place
  ~ resource "databricks_job" "this" {
        id                        = "826499161150211"
      ~ max_retries               = 0 -> 2
        name                      = "Job with multiple tasks"
        # (7 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
}
```

### Terraform and provider versions
Terraform v1.4.6
on darwin_arm64
+ provider registry.terraform.io/databricks/databricks v1.30.0

### Debug Output
```bash
2023-12-01T16:43:26.703+0100 [WARN]  Provider "provider[\"registry.terraform.io/databricks/databricks\"]" produced an unexpected new value for databricks_job.this, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .max_retries: was cty.NumberIntVal(2), but now cty.NumberIntVal(0)
      - .min_retry_interval_millis: was null, but now cty.NumberIntVal(0)
      - .retry_on_timeout: was null, but now cty.False
      - .timeout_seconds: was null, but now cty.NumberIntVal(0)
      - .email_notifications: block count changed from 0 to 1
      - .task[0].job_cluster_key: was null, but now cty.StringVal("")
      - .task[0].min_retry_interval_millis: was null, but now cty.NumberIntVal(0)
      - .task[0].description: was null, but now cty.StringVal("")
      - .task[0].existing_cluster_id: was null, but now cty.StringVal("")
      - .task[0].run_if: was null, but now cty.StringVal("ALL_SUCCESS")
      - .task[0].timeout_seconds: was null, but now cty.NumberIntVal(0)
      - .task[0].compute_key: was null, but now cty.StringVal("")
      - .task[0].max_retries: was null, but now cty.NumberIntVal(0)
      - .task[0].new_cluster[0].runtime_engine: was null, but now cty.StringVal("")
      - .task[0].new_cluster[0].cluster_id: was null, but now cty.StringVal("")
      - .task[0].new_cluster[0].data_security_mode: was null, but now cty.StringVal("")
      - .task[0].new_cluster[0].idempotency_token: was null, but now cty.StringVal("")
      - .task[0].new_cluster[0].autotermination_minutes: was null, but now cty.NumberIntVal(0)
      - .task[0].new_cluster[0].cluster_name: was null, but now cty.StringVal("")
      - .task[0].new_cluster[0].instance_pool_id: was null, but now cty.StringVal("")
      - .task[0].new_cluster[0].policy_id: was null, but now cty.StringVal("")
      - .task[0].new_cluster[0].apply_policy_default_values: was null, but now cty.False
      - .task[0].new_cluster[0].single_user_name: was null, but now cty.StringVal("")
      - .task[0].new_cluster[0].azure_attributes: block count changed from 0 to 1
      - .task[0].email_notifications: block count changed from 0 to 1
      - .task[0].notebook_task[0].source: was null, but now cty.StringVal("WORKSPACE")
      - .webhook_notifications: block count changed from 0 to 1
```

### LINKED ISSUE #3032: Error when running terraform apply for a job with job-level parameters in API version 2.1
I am encountering an issue when executing terraform apply for a specific job that includes job-level parameters. The error message indicates that these parameters are only available in API version 2.1. However, other jobs within the same repository are configured similarly and do not raise any issues.

image

Steps to Reproduce:
 file with the job:

```hcl
resource "databricks_job" "infra_analytics_compute_metrics" {
  max_concurrent_runs = 100
  name                = "infra_analytics_compute_metrics"
  tags = {
    "environment" = "dev"
    "propose"     = "metrics"
  }
  timeout_seconds = 3600

  git_source {
    branch   = "master"
    provider = "gitHub"
    url      = "my_url"
  }

  new_cluster {
    apply_policy_default_values = false
    autotermination_minutes     = 0
    custom_tags = {
      "ResourceClass" = "SingleNode"
    }
    data_security_mode           = "SINGLE_USER"
    driver_node_type_id          = "i3.2xlarge"
    enable_elastic_disk          = true
    enable_local_disk_encryption = false
    node_type_id                 = "i3.2xlarge"
    num_workers                  = 0
    runtime_engine               = "STANDARD"
    spark_conf = {
      "spark.databricks.cluster.profile" = "singleNode"
      "spark.master"                     = "local[*, 4]"
    }
    spark_env_vars  = {}
    spark_version   = "12.2.x-scala2.12"
    ssh_public_keys = []

    autoscale {
      max_workers = 10
      min_workers = 2
    }

    aws_attributes {
      availability           = "SPOT_WITH_FALLBACK"
      ebs_volume_count       = 0
      ebs_volume_size        = 0
      first_on_demand        = 11
      instance_profile_arn   = "my_instance_profile_arn"
      spot_bid_price_percent = 100
      zone_id                = "auto"
    }
  }

  notebook_task {
    base_parameters = {
      "DATALAKE_VERSION"         = "2.0"
      "DELTA_DATABASE"           = "infracommerce"
      "ENVIRONMENT"              = "{{job.parameters.ENVIRONMENT}}"
      "S3_ROOT_FOLDER"           = ""
      "TENANT"                           = "{{job.parameters.TENANT}}"
      "INACTIVE_LOCATION_ROLES"  = "{{job.parameters.INACTIVE_LOCATION_ROLES}}"
    }
    notebook_path = "my_path"
    source        = "GIT"
  }

  notification_settings {


  }

  parameter {
    default = "2.0"
    name    = "DATALAKE_VERSION"
  }
  parameter {
    default = ""
    name    = "DELTA_DATABASE"
  }
  parameter {
    default = "False"
    name    = "DISCOVERY_SUPPLY_LINKS"
  }
  parameter {
    default = ""
    name    = "ENVIRONMENT"
  }
  parameter {
    default = "False"
    name    = "IGNORE_INCOMMING_SELLIN"
  }
  parameter {
    default = "96"
    name    = "LIVE_DATA_PERIOD"
  }
  parameter {
    default = ""
    name    = "S3_ROOT_FOLDER"
  }
  parameter {
    default = "False"
    name    = "SUPPLY_RESTRICTIONS_ENABLE"
  }
  parameter {
    default = " "
    name    = "TENANT"
  }
  parameter {
    name = "INACTIVE_LOCATION_ROLES"
    default = " "
  }
}
```

Run terraform apply for the affected job.
Observe the error message regarding job-level parameters and API version.

Environment Details:

Terraform Version: 1.30.0 (I also tried the 1.31.1 version)

I appreciate your assistance in resolving this matter. Let me know if further information is needed.

Thank you!

### PR DESCRIPTION
**Pull request by 840**
## Changes
Deprecate top level task attributes inside a `databricks_job` resource.
- `max_retries`
- `min_retry_interval_millis`
- `retry_on_timeout`
- `notebook_task`
- `spark_jar_task`
- `spark_python_task`
- `spark_submit_task`
- `pipeline_task`
- `python_wheel_task`
- `dbt_task`
- `run_job_task`

These should be defined inside a task block, instead.

Fixes #2978, fixes #3032, 

## Tests
Tried `terraform apply` and it correctly states the attributes are deprecated.

- [x] `make test` run locally
- [ ] relevant change in `docs/` folder
- [ ] covered with integration tests in `internal/acceptance`
- [ ] relevant acceptance tests are passing
- [ ] using Go SDK

### CODE REVIEW

**Comment by alexott** [comment]
I'm thinking if we should deprecate top-level tasks & other related objects as well?

**Comment by 840** [comment]
Added deprecations to top-level tasks and `min_retry_interval_millis`.

**Review by alexott — COMMENTED** [review]
Please modify the documentation as well - it's saying `legacy` now, but it's better to explicitly say "Deprecated". Otherwise, code changes are good.

**Comment by alexott** [comment]
@840 can you please update documentation so we can merge this PR? It will help with issues like #3032

**Comment by 840** [comment]
@alexott updated the documentation

**Review by alexott — APPROVED** [review]

**Review by mgyucht — APPROVED** [review]

**Pull request merged**
