### PR TITLE
Update jobs library fields from set to list

### PR DESCRIPTION
**Pull request by edwardfeng-db**
## Changes

- Ordering is important, updating the library fields in jobs schema from set to list
- Previously it wasn't updated because during the go-sdk schema migration we wanted to minimize breaking schema changes

## Tests

- [x] `make test` run locally
- [ ] relevant change in `docs/` folder
- [x] covered with integration tests in `internal/acceptance`
- [x] relevant acceptance tests are passing
- [x] using Go SDK

### CODE REVIEW

**Review by pietern — COMMENTED** [review]
LGTM

Can this schema evolution happen automatically? I believe the underlying representation of a list or a set is the same, so suspect it should be fine, but could you double-check with an existing deployment with 2+ libraries, and then redeploying with this change?

**Comment by hectorcast-db** [comment]
LGMT. What is the impact in customers? Will this cause an update on the TF resources?

**Comment by edwardfeng-db** [comment]
Tested it out locally, I see that there'll be a diff for the ordering @hectorcast-db @pietern, but I'm not sure if this is considered a breaking thing for customers

>       ~ library {
>           ~ jar = "dbfs://ff/gg/hh.jar" -> "dbfs://aa/bb/cc.jar"
>         }
>       ~ library {
>           ~ jar = "dbfs://aa/bb/cc.jar" -> "dbfs://ff/gg/hh.jar"
>         }

**Review by hectorcast-db — APPROVED** [review]
We should add a note in the release notifying of possible diffs and updates.

**Comment by alexott** [comment]
We need to be careful with slice set and complex blocks - we already had an issue with DLT pipelines: https://github.com/databricks/terraform-provider-databricks/issues/1401 - we need to test for `pypi` blocks, and similar things and make sure that it won't cause the configuration drift

**Pull request merged**
