### PR TITLE
Update Go SDK to latest + Fix backwards incompatible change

### PR DESCRIPTION
**Pull request by tanmay-db**
## Changes

Updating Go SDK to new release https://github.com/databricks/databricks-sdk-go/releases/tag/v0.34.0 and fixing backwards incompatible changes

## Tests

Unit tests, triggered nightly run.
- [x] `make test` run locally
- [ ] relevant change in `docs/` folder
- [ ] covered with integration tests in `internal/acceptance`
- [ ] relevant acceptance tests are passing
- [ ] using Go SDK

### CODE REVIEW

**Comment by hectorcast-db** [comment]
Code and tests need update to use the nested Settings.

**Comment by tanmay-db** [comment]
yeah

**Review by alexott — APPROVED** [review]
code-wise looks good to me

**Comment by alexott** [comment]
Failures in nighties are well-known:
* Hitting the limit on the number of vector search instances - should be addressed by #3348
* Lakehouse Monitoring doesn't work on GCP yet - should be fixed by #3355

**Review by edwardfeng-db — APPROVED** [review]

**Pull request merged**
