### PR TITLE
Fixed InitScripts Type to work with GCS and ABFS.

### PR DESCRIPTION
**Pull request by martinzuern**
On Azure and GCP, InitScripts can be pulled from their respective Cloud Storage offerings. However due to the wrong type, when refreshing only DBFS and S3 are considered, leading to diffs (where in reality there is no diff). 

This PR updates the type so that also ABFS and GCS InitScripts are considered on refresh.

### CODE REVIEW

**Comment by nkvuong** [comment]
@martinzuern do you mind adding a unit test that covers this?

**Comment by martinzuern** [comment]
@nkvuong added a test

**Comment by martinzuern** [comment]
Is there anything else you need from my side to get it merged? Would be thrilled if it makes it into the next release. @nkvuong

**Review by alexott — APPROVED** [review]
lgtm. thank you!

**Review by nfx — APPROVED** [review]

**Pull request merged**
