### PR TITLE
Extending customizable schema with `AtLeastOneOf`, `ExactlyOneOf`, `RequiredWith`

### PR DESCRIPTION
**Pull request by karolusz**
## Changes
Allowing `AtLeastOneOf`, `ExactlyOneOf` and `RequiredWith` to be set  on resource schema in `customizable_schema.go`.
These are desirable schema customizations that were missing in PR #3076 

This follows the discussion from PR #3178

## Tests
`customizable_schema.go` doesn't have unit test to begin with. I don't know if Databricks team is planning on creating those test at a later stage.

- [x] `make test` run locally
- [ ] relevant change in `docs/` folder
- [ ] covered with integration tests in `internal/acceptance`
- [ ] relevant acceptance tests are passing
- [ ] using Go SDK

### CODE REVIEW

**Review by mgyucht — APPROVED** [review]
Great, thanks for this contribution!

**Review by edwardfeng-db — APPROVED** [review]
Thank you!

**Comment by edwardfeng-db** [comment]
@karolusz Can you add some unit test cases following this PR for the new methods you added? Thanks!

https://github.com/databricks/terraform-provider-databricks/pull/3192

**Comment by karolusz** [comment]
> @karolusz Can you add some unit test cases following this PR for the new methods you added? Thanks!
> 
> #3192

No problem. I will try to find some time today or tomorrow.

**Review by edwardfeng-db — APPROVED** [review]
Thanks! Unit tests look good

**Review by alexott — APPROVED** [review]

**Pull request merged**
