### PR TITLE
Improve test coverage of multitask jobs & DLT pipelines

### PR DESCRIPTION
**Pull request by alexott**

### CODE REVIEW

**Comment by nfx** [comment]
@alexott could you also increase the coverage of exporter/util.go to 90%?

**Review by nfx — CHANGES_REQUESTED** [review]
Nice! Thank you. Please also increase the coverage for exporter/util.go to 90%

**Comment by alexott** [comment]
Not this time, primary things that aren't covered are error handling in the complex conditions...

**Comment by nfx** [comment]
Complex conditions are more likely to break. If you’re concerned about the size of testing code - look at how individual Imports on importables are tested. There is a special helper to test for what is emitted without causing any downstream requests

**Comment by alexott** [comment]
I’m not concerned about testing code size, I’m concerned about my time for that. Feel free to to revert previous PR.

**Review by nfx — APPROVED** [review]

**Pull request merged**
