### PR TITLE
Add databricks_compliance_security_profile_workspace_setting resource

### PR DESCRIPTION
**Pull request by harshshah-db**
## Tests

- [x] `make test` run locally
- [x] relevant change in `docs/` folder
- [ ] covered with integration tests in `internal/acceptance`
- [ ] relevant acceptance tests are passing
- [x] using Go SDK

### CODE REVIEW

**Comment by harshshah-db** [comment]
Hi @tanmay-db @alexott @nkvuong @hectorcast-db  the test in this PR fails with the following error
```
=== Failed
=== FAIL: settings TestQueryCreateComplianceSecurityProfileSettingWithNoneStandard (0.00s)
    resource_compliance_security_profile_setting_test.go:82:
        	Error Trace:	/Users/harsh.shah/terraform-provider-databricks/settings/resource_compliance_security_profile_setting_test.go:82
        	Error:      	Received unexpected error:
        	            	compliance_security_profile_workspace: compliance_security_profile_workspace: compliance_standards: [compliance_standards]: not resource
        	Test:       	TestQueryCreateComplianceSecurityProfileSettingWithNoneStandard
        	```

**Comment by nkvuong** [comment]
> Hi @tanmay-db @alexott @nkvuong @hectorcast-db the test in this PR fails with the following error. Any idea what could be wrong? I already spent hours trying a bunch of stuff but I suspect I am not defining the `compliance_standards` field properly. Would appreciate any advice/insight.
> 
> ```
> === Failed
> === FAIL: settings TestQueryCreateComplianceSecurityProfileSettingWithNoneStandard (0.00s)
>     resource_compliance_security_profile_setting_test.go:82:
>         	Error Trace:	/Users/harsh.shah/terraform-provider-databricks/settings/resource_compliance_security_profile_setting_test.go:82
>         	Error:      	Received unexpected error:
>         	            	compliance_security_profile_workspace: compliance_security_profile_workspace: compliance_standards: [compliance_standards]: not resource
>         	Test:       	TestQueryCreateComplianceSecurityProfileSettingWithNoneStandard
>   
> ```

the issue is with https://github.com/databricks/terraform-provider-databricks/blob/31df20c094cef22242ec6e43f3536ba2719e2bb8/common/reflect_resource.go#L631

basically it tries to convert https://github.com/databricks/databricks-sdk-go/blob/27d08a67df5b0d35544c663f9d47577f85ffc6e4/service/settings/model.go#L199 to a Terraform resource and crashed. `[]ComplianceStandard` crashed, but `[]string` does not.

@edwardfeng-db you last worked on this function, any thoughts?

**Comment by edwardfeng-db** [comment]
Yeah it seems kind of strange to me that this is a `[]ComplianceStandard` instead of `[]string`, @hectorcast-db is this autogenerated? Any idea why?

**Comment by edwardfeng-db** [comment]
Thanks @hectorcast-db, yeah this seems like a legit bug on the terraform side, I'll try to fix this

**Comment by harshshah-db** [comment]
> Thanks @hectorcast-db, yeah this seems like a legit bug on the terraform side, I'll try to fix this

@edwardfeng-db any ETA on the fix? This is blocking our public api launch which the customers have been asking for.

**Comment by edwardfeng-db** [comment]
@harshshah-db Hopefully today, still debugging

**Comment by edwardfeng-db** [comment]
Here's the fix - https://github.com/databricks/terraform-provider-databricks/pull/3581 Verified it works with the failing test

**Comment by harshshah-db** [comment]
@nkvuong and @alexott  - Could you please review this again?

**Review by alexott — APPROVED** [review]

**Pull request merged**
