### PR TITLE
Fix DiffSuppressFunc for `databricks_model_serving` resource

### LINKED ISSUE #2811: [ISSUE] Issue with `databricks_model_serving` resource - We can apply a GPU workload type when updating an existing endpoint but not when creating a new one from scratch.
We can apply a GPU workload type when updating an existing endpoint but not when creating a new one from scratch.

### Configuration
```hcl
resource "databricks_model_serving" "this" {
  name = "simple-endpoint"
  config {
    served_models {
      name                  = "prod_model"
      model_name            = "wine_quality_tommcm"
      model_version         = "2"
      workload_size         = "Small"
      workload_type         = "GPU_MEDIUM"
      scale_to_zero_enabled = false
    }
  }
}
```

### Expected Behavior
Create model serving endpoint with GPU_MEDIUM workload type.

Expected API response:
```hcl
{
 "config": {
  "config_version":2,
  "served_models": [
   {
    "creation_timestamp":1697513832000,
    "creator":"tom.mcmeekin@databricks.com",
    "model_name":"wine_quality_tommcm",
    "model_version":"2",
    "name":"prod_model",
    "scale_to_zero_enabled":false,
    "state": {
     "deployment":"DEPLOYMENT_READY",
     "deployment_state_message":""
    },
    "workload_size":"Small",
    "workload_type":"GPU_MEDIUM"
   }
  ],
  "traffic_config": {
   "routes": [
    {
     "served_model_name":"prod_model",
     "traffic_percentage":100
    }
   ]
  }
 },
 "creation_timestamp":1697513436000,
 "creator":"tom.mcmeekin@databricks.com",
 "id":"###########REMOVED#########",
 "last_updated_timestamp":1697513832000,
 "name":"simple-endpoint",
 "permission_level":"CAN_MANAGE",
 "state": {
  "config_update":"NOT_UPDATING",
  "ready":"READY"
 }
}
```

### Actual Behavior
We can apply a GPU workload type when updating an existing endpoint but not when creating a new one from scratch.

TF return plan:
```hcl
# databricks_model_serving.this will be created
 + resource "databricks_model_serving" "this" {
   + id         = (known after apply)
   + name        = "simple-endpoint"
   + serving_endpoint_id = (known after apply)

   + config {
     + served_models {
       + model_name      = "wine_quality_tommcm"
       + model_version     = "2"
       + name         = "prod_model"
       + scale_to_zero_enabled = false
       + workload_size     = "Small"
      }
    }
  }
```

```hcl
{
 "config": {
  "config_version":1,
  "served_models": [
   {
    "creation_timestamp":1697513436000,
    "creator":"tom.mcmeekin@databricks.com",
    "model_name":"wine_quality_tommcm",
    "model_version":"2",
    "name":"prod_model",
    "scale_to_zero_enabled":false,
    "state": {
     "deployment":"DEPLOYMENT_READY",
     "deployment_state_message":""
    },
    "workload_size":"Small",
    "workload_type":"CPU"
   }
  ],
  "traffic_config": {
   "routes": [
    {
     "served_model_name":"prod_model",
     "traffic_percentage":100
    }
   ]
  }
 },
 "creation_timestamp":1697513436000,
 "creator":"tom.mcmeekin@databricks.com",
 "id":"###########REMOVED#########",
 "last_updated_timestamp":1697513436000,
 "name":"simple-endpoint",
 "permission_level":"CAN_MANAGE",
 "state": {
  "config_update":"NOT_UPDATING",
  "ready":"READY"
 }
}
```

### Steps to Reproduce
1. `terraform apply`
2. Model serving endpoint is created with default CPU workload type
3. `terraform apply`
4. Model serving endpoint is updated with GPU workload type

### Terraform and provider versions
1.28.0

### Debug Output

```
2023-10-18T08:45:20.820+1100 [DEBUG] provider: starting plugin: path=.terraform/providers/registry.terraform.io/databricks/databricks/1.28.0/darwin_arm64/terraform-provider-databricks_v1.28.0 args=[.terraform/providers/registry.terraform.io/databricks/databricks/1.28.0/darwin_arm64/terraform-provider-databricks_v1.28.0]
path=.terraform/providers/registry.terraform.io/databricks/databricks/1.28.0/darwin_arm64/terraform-provider-databricks_v1.28.0 pid=3773
2023-10-18T08:45:20.823+1100 [DEBUG] provider: waiting for RPC address: path=.terraform/providers/registry.terraform.io/databricks/databricks/1.28.0/darwin_arm64/terraform-provider-databricks_v1.28.0
2023-10-18T08:45:20.843+1100 [DEBUG] provider.terraform-provider-databricks_v1.28.0: Databricks Terraform Provider
2023-10-18T08:45:20.843+1100 [DEBUG] provider.terraform-provider-databricks_v1.28.0: 
2023-10-18T08:45:20.843+1100 [DEBUG] provider.terraform-provider-databricks_v1.28.0: Version 1.28.0
2023-10-18T08:45:20.843+1100 [DEBUG] provider.terraform-provider-databricks_v1.28.0: 
2023-10-18T08:45:20.843+1100 [DEBUG] provider.terraform-provider-databricks_v1.28.0: https://registry.terraform.io/providers/databricks/databricks/latest/docs
2023-10-18T08:45:20.843+1100 [DEBUG] provider.terraform-provider-databricks_v1.28.0: 
2023-10-18T08:45:20.844+1100 [INFO]  provider.terraform-provider-databricks_v1.28.0: configuring server automatic mTLS: timestamp=2023-10-18T08:45:20.844+1100
address=/var/folders/dz/3hdk58850lgcb3tp_fbm3gyw0000gp/T/plugin3360407781 network=unix timestamp=2023-10-18T08:45:20.858+1100
path=.terraform/providers/registry.terraform.io/databricks/databricks/1.28.0/darwin_arm64/terraform-provider-databricks_v1.28.0 pid=3773
2023-10-18T08:45:21.386+1100 [DEBUG] ProviderTransformer: "databricks_model_serving.this" (*terraform.NodeValidatableResource) needs provider["registry.terraform.io/databricks/databricks"]
2023-10-18T08:45:21.387+1100 [DEBUG] ReferenceTransformer: "databricks_model_serving.this" references: []
2023-10-18T08:45:21.387+1100 [DEBUG] ReferenceTransformer: "var.databricks_connection_profile" references: []
2023-10-18T08:45:21.387+1100 [DEBUG] ReferenceTransformer: "provider[\"registry.terraform.io/databricks/databricks\"]" references: [var.databricks_connection_profile]
2023-10-18T08:45:21.390+1100 [DEBUG] provider: starting plugin: path=.terraform/providers/registry.terraform.io/databricks/databricks/1.28.0/darwin_arm64/terraform-provider-databricks_v1.28.0 args=[.terraform/providers/registry.terraform.io/databricks/databricks/1.28.0/darwin_arm64/terraform-provider-databricks_v1.28.0]
path=.terraform/providers/registry.terraform.io/databricks/databricks/1.28.0/darwin_arm64/terraform-provider-databricks_v1.28.0 pid=3775
2023-10-18T08:45:21.392+1100 [DEBUG] provider: waiting for RPC address: path=.terraform/providers/registry.terraform.io/databricks/databricks/1.28.0/darwin_arm64/terraform-provider-databricks_v1.28.0
2023-10-18T08:45:21.408+1100 [DEBUG] provider.terraform-provider-databricks_v1.28.0: Databricks Terraform Provider
2023-10-18T08:45:21.408+1100 [DEBUG] provider.terraform-provider-databricks_v1.28.0: 
2023-10-18T08:45:21.408+1100 [DEBUG] provider.terraform-provider-databricks_v1.28.0: Version 1.28.0
2023-10-18T08:45:21.408+1100 [DEBUG] provider.terraform-provider-databricks_v1.28.0: 
2023-10-18T08:45:21.408+1100 [DEBUG] provider.terraform-provider-databricks_v1.28.0: https://registry.terraform.io/providers/databricks/databricks/latest/docs
2023-10-18T08:45:21.408+1100 [DEBUG] provider.terraform-provider-databricks_v1.28.0: 
2023-10-18T08:45:21.409+1100 [INFO]  provider.terraform-provider-databricks_v1.28.0: configuring server automatic mTLS: timestamp=2023-10-18T08:45:21.409+1100
address=/var/folders/dz/3hdk58850lgcb3tp_fbm3gyw0000gp/T/plugin2570285707 network=unix timestamp=2023-10-18T08:45:21.422+1100
path=.terraform/providers/registry.terraform.io/databricks/databricks/1.28.0/darwin_arm64/terraform-provider-databricks_v1.28.0 pid=3775
2023-10-18T08:45:21.442+1100 [DEBUG] ProviderTransformer: "databricks_model_serving.this (expand)" (*terraform.nodeExpandPlannableResource) needs provider["registry.terraform.io/databricks/databricks"]
2023-10-18T08:45:21.442+1100 [DEBUG] ReferenceTransformer: "databricks_model_serving.this (expand)" references: []
2023-10-18T08:45:21.442+1100 [DEBUG] ReferenceTransformer: "var.databricks_connection_profile" references: []
2023-10-18T08:45:21.442+1100 [DEBUG] ReferenceTransformer: "provider[\"registry.terraform.io/databricks/databricks\"]" references: [var.databricks_connection_profile]
2023-10-18T08:45:21.445+1100 [DEBUG] provider: starting plugin: path=.terraform/providers/registry.terraform.io/databricks/databricks/1.28.0/darwin_arm64/terraform-provider-databricks_v1.28.0 args=[.terraform/providers/registry.terraform.io/databricks/databricks/1.28.0/darwin_arm64/terraform-provider-databricks_v1.28.0]
path=.terraform/providers/registry.terraform.io/databricks/databricks/1.28.0/darwin_arm64/terraform-provider-databricks_v1.28.0 pid=3776
2023-10-18T08:45:21.448+1100 [DEBUG] provider: waiting for RPC address: path=.terraform/providers/registry.terraform.io/databricks/databricks/1.28.0/darwin_arm64/terraform-provider-databricks_v1.28.0
2023-10-18T08:45:21.466+1100 [DEBUG] provider.terraform-provider-databricks_v1.28.0: Databricks Terraform Provider
2023-10-18T08:45:21.466+1100 [DEBUG] provider.terraform-provider-databricks_v1.28.0: 
2023-10-18T08:45:21.466+1100 [DEBUG] provider.terraform-provider-databricks_v1.28.0: Version 1.28.0
2023-10-18T08:45:21.466+1100 [DEBUG] provider.terraform-provider-databricks_v1.28.0: 
2023-10-18T08:45:21.466+1100 [DEBUG] provider.terraform-provider-databricks_v1.28.0: https://registry.terraform.io/providers/databricks/databricks/latest/docs
2023-10-18T08:45:21.466+1100 [DEBUG] provider.terraform-provider-databricks_v1.28.0: 
2023-10-18T08:45:21.467+1100 [INFO]  provider.terraform-provider-databricks_v1.28.0: configuring server automatic mTLS: timestamp=2023-10-18T08:45:21.467+1100
network=unix address=/var/folders/dz/3hdk58850lgcb3tp_fbm3gyw0000gp/T/plugin1333835326 timestamp=2023-10-18T08:45:21.480+1100
2023-10-18T08:45:21.497+1100 [WARN]  ValidateProviderConfig from "provider[\"registry.terraform.io/databricks/databricks\"]" changed the config value, but that value is unused
2023-10-18T08:45:21.498+1100 [INFO]  provider.terraform-provider-databricks_v1.28.0: Explicit and implicit attributes: profile: timestamp=2023-10-18T08:45:21.498+1100
2023-10-18T08:45:21.498+1100 [DEBUG] Resource instance state not found for node "databricks_model_serving.this", instance databricks_model_serving.this
2023-10-18T08:45:21.498+1100 [DEBUG] ReferenceTransformer: "databricks_model_serving.this" references: []
2023-10-18T08:45:21.498+1100 [DEBUG] refresh: databricks_model_serving.this: no state, so not refreshing
2023-10-18T08:45:21.500+1100 [WARN]  Provider "registry.terraform.io/databricks/databricks" produced an invalid plan for databricks_model_serving.this, but we are tolerating it because it is using the legacy plugin SDK.
path=.terraform/providers/registry.terraform.io/databricks/databricks/1.28.0/darwin_arm64/terraform-provider-databricks_v1.28.0 pid=3776
2023-10-18T08:45:21.501+1100 [DEBUG] Resource state not found for node "databricks_model_serving.this", instance databricks_model_serving.this
2023-10-18T08:45:21.501+1100 [DEBUG] ProviderTransformer: "databricks_model_serving.this (expand)" (*terraform.nodeExpandApplyableResource) needs provider["registry.terraform.io/databricks/databricks"]
2023-10-18T08:45:21.501+1100 [DEBUG] ProviderTransformer: "databricks_model_serving.this" (*terraform.NodeApplyableResourceInstance) needs provider["registry.terraform.io/databricks/databricks"]
2023-10-18T08:45:21.501+1100 [DEBUG] ReferenceTransformer: "databricks_model_serving.this (expand)" references: []
2023-10-18T08:45:21.502+1100 [DEBUG] ReferenceTransformer: "var.databricks_connection_profile" references: []
2023-10-18T08:45:21.502+1100 [DEBUG] ReferenceTransformer: "databricks_model_serving.this" references: []
2023-10-18T08:45:21.502+1100 [DEBUG] ReferenceTransformer: "provider[\"registry.terraform.io/databricks/databricks\"]" references: [var.databricks_connection_profile]
  # databricks_model_serving.this will be created
  + resource "databricks_model_serving" "this" {
```

### PR DESCRIPTION
**Pull request by nkvuong**
## Changes
Closes #2811

## Tests

- [x] `make test` run locally
- [x] covered with integration tests in `internal/acceptance`
- [x] relevant acceptance tests are passing
- [x] using Go SDK

### CODE REVIEW

**Review by alexott — APPROVED** [review]

**Comment by alexott** [comment]
But with the `Default`, do we really need a suppress diff?

**Comment by nkvuong** [comment]
@alexott the problem is on Azure, where GPU serving is not enabled, the API returns empty `workload_type`...

**Comment by alexott** [comment]
and yeah, then we'll have GCP

**Comment by mgyucht** [comment]
@nkvuong can we do the following instead:
```go
			common.MustSchemaPath(m, "config", "served_models", "workload_type").Computed = true
			common.MustSchemaPath(m, "config", "served_models", "workload_type").Optional = true
```
That way, if the user doesn't specify, we fall back to the API default (which could be empty, as in Azure), and if they remove the value, it would keep its original value. I'm just so confused by DiffSuppressFunc... I'm going to try to repro now and use this change.

**Review by mgyucht — APPROVED** [review]
We can move forward with this as-is. I think we need to revisit how we use Computed/Optional vs DiffSuppressFunc in the future; in the meantime, let's just add a comment here, and merge.

**Pull request merged**
