### PR TITLE
Fix sql table column type upper and lower mismatch error

### PR DESCRIPTION
**Pull request by case-k-git**
## Changes

Terraform manage column type by lower case so if add the Upper case terraform 
Terraform manages column types in lowercase, so passing them in uppercase results in a column mismatch error.Even if not changing column type

fix this error 
https://github.com/databricks/terraform-provider-databricks/issues/3490
## Tests

- [x] `make test` run locally
- [ ] relevant change in `docs/` folder
- [ ] covered with integration tests in `internal/acceptance`
- [x] relevant acceptance tests are passing
- [x] using Go SDK

### CODE REVIEW

**Comment by tanmay-db** [comment]
Hi @case-k-git, thanks for creating the PR, there were other issues that needed to be fixed (mapping) and I have created the PR to include this along with integration test: https://github.com/databricks/terraform-provider-databricks/pull/3528. 

Once that is merged, can you please rebase and your PR with unit test can be merged after it.

**Comment by case-k-git** [comment]
Hi @tanmay-db Thank you for your comment. Sure!!

**Comment by case-k-git** [comment]
Hi @tanmay-db 
Resolve the conflict. Could you please check when you have time? Thank you.

```
--- PASS: TestResourceSqlTableUpdateTable_ColumnsTypeUpperLowerCaseThrowsError (0.54s)
PASS
ok  	github.com/databricks/terraform-provider-databricks/catalog	(cached)
```

**Comment by tanmay-db** [comment]
Hi @case-k-git, thanks for the PR.

**Review by tanmay-db — APPROVED** [review]

**Pull request merged**
