### PR TITLE
Remove and update default params for serving

### PR DESCRIPTION
**Pull request by arpitjasa-db**
## Changes

Remove and update default params since the backend will handle this.

## Tests

- [X] `make test` run locally
- [X] relevant change in `docs/` folder
- [X] covered with integration tests in `internal/acceptance`
- [ ] relevant acceptance tests are passing
- [X] using Go SDK

### CODE REVIEW

**Review by ankit-db — APPROVED** [review]

**Review by AarushiShah-db — COMMENTED** [review]
lgtm, api/backend handles these cases for PT, and custom (CPU/GPU) serving

**Review by alexott — CHANGES_REQUESTED** [review]
We need to add more acceptance tests to make sure that this and future changes won't cause issues - right now, there is a very simple acceptance test that doesn't cover provisioned throughput functionality...

**Comment by alexott** [comment]
Unfortunately, the `system.ai.dbrx_instruct` isn't enabled in the test workspaces yet...

**Comment by alexott** [comment]
tests passed on Azure, on AWS we may still need to wait until `system.ai` rollout...

**Review by alexott — APPROVED** [review]

**Review by hectorcast-db — APPROVED** [review]

**Pull request merged**
