### PR TITLE
[Feature] Added support to use protocol version 6 provider server for SDK plugin

### PR DESCRIPTION
**Pull request by tanmay-db**
## Changes

Upgrade SDK plugin to use protocol version 6 as this will be used further for introducing plugin framework. We need to mux them (i.e. support both sdkv2 and plugin framework) until all resources are migrated to plugin framework.

Reference for PR on main branch: https://github.com/databricks/terraform-provider-databricks/pull/3714, this PR against the main branch will be used to get the binary for testing with data team.

## Tests

All Unit and Integration test passed.
- [x] `make test` run locally
- [ ] relevant change in `docs/` folder
- [ ] covered with integration tests in `internal/acceptance`
- [x] relevant acceptance tests are passing
- [ ] using Go SDK

### CODE REVIEW

**Review by renaudhartert-db — COMMENTED** [review]
@tanmay-db, I just left a few comments mostly about how I think we can slightly improve the code's readability. These are optional so please feel free to ignore them.

**Review by edwardfeng-db — APPROVED** [review]
LGTM, but I think it'd be good to address Renaud's commands

**Comment by tanmay-db** [comment]
Yes, I will be addressing @renaudhartert-db's  comments, just wanted to check if any core change needs to be updated since there are some conflicts (and this branch lags main branch so more conflicts) so I planned to address them simultaneously.

**Comment by tanmay-db** [comment]
Hi Team, catching up back on this PR. Comments have been addressed, waiting for https://github.com/databricks/terraform-provider-databricks/pull/3780/ to merge before merging this.

**Pull request merged**
