### PR TITLE
Fixed multidomain `databricks_user` in exporter

### PR DESCRIPTION
**Pull request by rohitnijhawan**
Fix for issue #1688
Issue with exporter emittingdatabricks_user resource - unable to handle multidomain

### CODE REVIEW

**Review by nfx — CHANGES_REQUESTED** [review]
code looks good, make sure that build is passing properly

**Review by alexott — CHANGES_REQUESTED** [review]
I can't push into the PR branch directly, here are required changes to avoid compiling on each invocation + add documentation

```
diff --git a/docs/guides/experimental-exporter.md b/docs/guides/experimental-exporter.md
index 655ac5c2..f18b9155 100644
--- a/docs/guides/experimental-exporter.md
+++ b/docs/guides/experimental-exporter.md
@@ -43,6 +43,7 @@ All arguments are optional and they tune what code is being generated.
 * `-generateProviderDeclaration` - flag that toggles generation of `databricks.tf` file with declaration of the Databricks Terraform provider that is necessary for Terraform versions since Terraform 0.13 (disabled by default).
 * `-prefix` - optional prefix that will be added to the name of all exported resources - that's useful for exporting resources multiple workspaces for merging into a single one.
 * `-skip-interactive` - optionally run in a non-interactive mode.
+* `-includeUserDomains` - optionally include domain name into generated resource name for `databricks_user` resource.

 ## Services

diff --git a/exporter/importables.go b/exporter/importables.go
index b4ae7c35..0be179a5 100644
--- a/exporter/importables.go
+++ b/exporter/importables.go
@@ -37,7 +37,7 @@ var (
 	s3Regex                 = regexp.MustCompile(`^(s3a?)://([^/]+)(/.*)?$`)
 	gsRegex                 = regexp.MustCompile(`^gs://([^/]+)(/.*)?$`)
 	globalWorkspaceConfName = "global_workspace_conf"
-	notebookPathToIdRegex   = regexp.MustCompile(`[^a-zA-Z0-9]+`)
+	nameNormalizationRegex  = regexp.MustCompile(`\W+`)
 	jobClustersRegex        = regexp.MustCompile(`^((job_cluster|task)\.[0-9]+\.new_cluster\.[0-9]+\.)`)
 	dltClusterRegex         = regexp.MustCompile(`^(cluster\.[0-9]+\.)`)
 )
@@ -659,13 +659,12 @@ var resourcesMap map[string]importable = map[string]importable{
 	"databricks_user": {
 		Service: "users",
 		Name: func(ic *importContext, d *schema.ResourceData) string {
-			//this checks CLI argument includeUserDomains,
-			//and in the case of users from multiple domains, it names resources differently
 			s := d.Get("user_name").(string)
+			// if CLI argument includeUserDomains is set then it includes domain portion as well
 			if ic.includeUserDomains {
-				return regexp.MustCompile(`\W+`).ReplaceAllString(s, "_")
+				return nameNormalizationRegex.ReplaceAllString(s, "_")
 			}
-			return regexp.MustCompile(`\W+`).ReplaceAllString(strings.Split(s, "@")[0], "_")
+			return nameNormalizationRegex.ReplaceAllString(strings.Split(s, "@")[0], "_")
 		},
 		Search: func(ic *importContext, r *resource) error {
 			u, err := ic.findUserByName(r.Value)
@@ -1023,7 +1022,7 @@ var resourcesMap map[string]importable = map[string]importable{
 			if name == "" {
 				return d.Id()
 			} else {
-				name = notebookPathToIdRegex.ReplaceAllString(name[1:], "_") + "_" +
+				name = nameNormalizationRegex.ReplaceAllString(name[1:], "_") + "_" +
 					strconv.FormatInt(int64(d.Get("object_id").(int)), 10)
 			}
 			return name
```

**Comment by rohitnijhawan** [comment]
> I can't push into the PR branch directly, here are required changes to avoid compiling on each invocation + add documentation
> 
> ```
> diff --git a/docs/guides/experimental-exporter.md b/docs/guides/experimental-exporter.md
> index 655ac5c2..f18b9155 100644
> --- a/docs/guides/experimental-exporter.md
> +++ b/docs/guides/experimental-exporter.md
> @@ -43,6 +43,7 @@ All arguments are optional and they tune what code is being generated.
>  * `-generateProviderDeclaration` - flag that toggles generation of `databricks.tf` file with declaration of the Databricks Terraform provider that is necessary for Terraform versions since Terraform 0.13 (disabled by default).
>  * `-prefix` - optional prefix that will be added to the name of all exported resources - that's useful for exporting resources multiple workspaces for merging into a single one.
>  * `-skip-interactive` - optionally run in a non-interactive mode.
> +* `-includeUserDomains` - optionally include domain name into generated resource name for `databricks_user` resource.
> 
>  ## Services
> 
> diff --git a/exporter/importables.go b/exporter/importables.go
> index b4ae7c35..0be179a5 100644
> --- a/exporter/importables.go
> +++ b/exporter/importables.go
> @@ -37,7 +37,7 @@ var (
>  	s3Regex                 = regexp.MustCompile(`^(s3a?)://([^/]+)(/.*)?$`)
>  	gsRegex                 = regexp.MustCompile(`^gs://([^/]+)(/.*)?$`)
>  	globalWorkspaceConfName = "global_workspace_conf"
> -	notebookPathToIdRegex   = regexp.MustCompile(`[^a-zA-Z0-9]+`)
> +	nameNormalizationRegex  = regexp.MustCompile(`\W+`)
>  	jobClustersRegex        = regexp.MustCompile(`^((job_cluster|task)\.[0-9]+\.new_cluster\.[0-9]+\.)`)
>  	dltClusterRegex         = regexp.MustCompile(`^(cluster\.[0-9]+\.)`)
>  )
> @@ -659,13 +659,12 @@ var resourcesMap map[string]importable = map[string]importable{
>  	"databricks_user": {
>  		Service: "users",
>  		Name: func(ic *importContext, d *schema.ResourceData) string {
> -			//this checks CLI argument includeUserDomains,
> -			//and in the case of users from multiple domains, it names resources differently
>  			s := d.Get("user_name").(string)
> +			// if CLI argument includeUserDomains is set then it includes domain portion as well
>  			if ic.includeUserDomains {
> -				return regexp.MustCompile(`\W+`).ReplaceAllString(s, "_")
> +				return nameNormalizationRegex.ReplaceAllString(s, "_")
>  			}
> -			return regexp.MustCompile(`\W+`).ReplaceAllString(strings.Split(s, "@")[0], "_")
> +			return nameNormalizationRegex.ReplaceAllString(strings.Split(s, "@")[0], "_")
>  		},
>  		Search: func(ic *importContext, r *resource) error {
>  			u, err := ic.findUserByName(r.Value)
> @@ -1023,7 +1022,7 @@ var resourcesMap map[string]importable = map[string]importable{
>  			if name == "" {
>  				return d.Id()
>  			} else {
> -				name = notebookPathToIdRegex.ReplaceAllString(name[1:], "_") + "_" +
> +				name = nameNormalizationRegex.ReplaceAllString(name[1:], "_") + "_" +
>  					strconv.FormatInt(int64(d.Get("object_id").(int)), 10)
>  			}
>  			return name
> ```

It looks like you have implemented the change before you can accept the PR. Do you want me to basically copy your change and then ask for a merge again?

**Comment by alexott** [comment]
Just copy that code into the file, and do `patch -p1 < ...path_to_file`, then commit & push into the same branch

**Review by nfx — APPROVED** [review]
lgtm, pending merge on @alexott approval

**Review by alexott — APPROVED** [review]
good now

**Comment by rohitnijhawan** [comment]
@nfx @alexott 

Can you please tell me what I need to do to get this one merged? This messes up my rebasing every time because model.go had changed in this.

**Review by nfx — APPROVED** [review]

**Pull request merged**
