### PR TITLE
Fixing some broken links

### PR DESCRIPTION
**Pull request by Chambras**
## Changes
This PR tries to fix this issue #3060 by updating the affected documents to point to the right link in the [troubleshooting guide](https://registry.terraform.io/providers/databricks/databricks/latest/docs/guides/troubleshooting)

## Tests

- [ ] `make test` run locally
- [x] relevant change in `docs/` folder
- [ ] covered with integration tests in `internal/acceptance`
- [ ] relevant acceptance tests are passing
- [ ] using Go SDK

### CODE REVIEW

**Review by alexott — CHANGES_REQUESTED** [review]
please don't use absolute links, use relative instead, like, `../guides/troubleshooting#data-resources-and-authentication-is-not-configured-errors`

**Comment by Chambras** [comment]
Hi @alexott 
Thanks for the feedback!
I did it so it would open in a new tab, and I also saw that in the same section some links also use absolute links.
Do you want me to update those as well so everything uses relative links instead of absolute?

**Comment by alexott** [comment]
Yes, we need to use relative links because they are automatically generated from Markdown, and we'll able to version the docs.

**Comment by Chambras** [comment]
Hi @alexott 
New update pushed to update links to use relative instead of absolute.

**Review by alexott — CHANGES_REQUESTED** [review]
`../guides/troubleshooting` should have file extension: `../guides/troubleshooting.md#...`

**Comment by Chambras** [comment]
sorry for the silly mistake @alexott should be fixed now. Happy new year!

**Review by alexott — APPROVED** [review]

**Comment by alexott** [comment]
Thank you for your contribution! Happy New Year!

**Pull request merged**
