### PR TITLE
Update `databricks_sql_endpoint` docs for Azure DBSQL Serverless GA - Part 2

### PR DESCRIPTION
**Pull request by jxbell**
## Changes

This is a followup to https://github.com/databricks/terraform-provider-databricks/pull/2249, which is already merged.

(1) Clarify enable_serverless_compute and warehouse_type rules from discussion in PR https://github.com/databricks/terraform-provider-databricks/pull/2249

(2) Last minute date change from engineering... change API date range for azure to ending May 19 (not 30)

## Tests

n/a doc changes only

### CODE REVIEW

**Comment by jxbell** [comment]
@alexott @nfx , please review PR changes

I don't have permissions to add you as reviewers directly on the PR...

cc: @mengqiu-teng @gaurav-pm @amji12

**Comment by jxbell** [comment]
@alexott @nfx we are a GO for May 3rd release. Please merge this PR (I'm not an authorized user to merge) and then please redeploy the terraform provider as appropriate for May 3rd -- I'm not sure whether that means you are doing things today or tomorrow may 3rd early morning, but I'm assuming with time zone issues it may be early on the 3rd, pacific time.

**Comment by jxbell** [comment]
@alexott @nfx  Heya, I noticed that this wasn't merged yet for yesterday’s release May 3rd. I request please merge this terraform PR (I’m not an authorized user to merge) and then please redeploy the terraform provider as appropriate. Thanks!

I'll repeat this request via Slack as well so it's easier to see, since I know you are busy and get lots of git notifications...

Thanks in advance!

cc: @jenniehubbardDB @amji12 @gaurav-db @mengqiu-teng

**Comment by alexott** [comment]
I don't have merge permissions as well... And publishing of the docs will require a full provider release. Maybe someone from @databricks/eng-dev-ecosystem can take care of it?

**Review by mgyucht — APPROVED** [review]

**Pull request merged**
